name: Stale preview

on:
  pull_request:
    paths:
      - .github/workflows/reusable-stale.yaml
      - .github/workflows/ops-stale.yaml
      - .github/workflows/stale-preview.yaml

permissions:
  issues: read
  pull-requests: read

jobs:
  stale:
    uses: ./.github/workflows/reusable-stale.yaml
    with:
      dry-run: true
